include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: ignore
    public_member_api_docs: ignore
    unnecessary_new: ignore
    avoid_init_to_null: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    unnecessary_getters_setters: ignore
    use_super_parameters: ignore
    library_private_types_in_public_api: ignore
    depend_on_referenced_packages: ignore
    body_might_complete_normally_nullable: ignore
    constant_identifier_names: ignore
    avoid_redundant_argument_values: ignore
    non_constant_identifier_names: ignore
    unused_field: ignore
    unnecessary_const: ignore
    unnecessary_import: ignore
    type_annotate_public_apis: ignore
    unused_import: ignore
    body_might_complete_normally: ignore
    empty_constructor_bodies: ignore
    undefined_annotation: ignore
    mixin_of_non_class: ignore
    prefer_const_constructors_in_immutables: ignore
    sized_box_for_whitespace: ignore
    sort_child_properties_last: ignore
    prefer_final_fields: ignore
    use_key_in_widget_constructors: ignore
    avoid_unnecessary_containers: ignore
    unused_local_variable: ignore

linter:
  rules:
    - avoid_print
    - public_member_api_docs
    - unnecessary_new
    - avoid_init_to_null
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - use_key_in_widget_constructors
    - avoid_redundant_argument_values
    - avoid_single_cascade_in_expression_statements
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - type_annotate_public_apis
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - unnecessary_lambdas
    - avoid_unnecessary_containers